import { chromium } from "playwright";
import http from "node:http"; import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs"; import { extname, join } from "node:path";
const ROOT=new URL("../_site/",import.meta.url).pathname;
const T={".html":"text/html",".css":"text/css",".js":"text/javascript",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2",".json":"application/json"};
const s=http.createServer(async(rq,rs)=>{try{let p=rq.url.split("?")[0];if(p.endsWith("/"))p+="index.html";let f=join(ROOT,p);if(!existsSync(f)&&existsSync(f+".html"))f+=".html";rs.writeHead(200,{"content-type":T[extname(f)]||"text/plain"});rs.end(await readFile(f));}catch{rs.writeHead(404);rs.end("x");}});
await new Promise(r=>s.listen(4556,r));
const EXE="/home/balnagowan/.cache/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell";
const b=await chromium.launch({executablePath:EXE,args:["--no-sandbox","--disable-gpu"]});
const pg=await b.newPage({viewport:{width:1440,height:900}});
await pg.goto("http://localhost:4556/",{waitUntil:"load"});
await pg.waitForTimeout(600);
const d=await pg.evaluate(()=>{const n=document.querySelector("nav");const sc=document.querySelector(".story-scroll");return {scrollTop:sc?Math.round(sc.scrollTop):"n/a",hasScrolledClass:n.classList.contains("nav-scrolled"),width:Math.round(n.getBoundingClientRect().width),vw:window.innerWidth,radius:getComputedStyle(n).borderTopLeftRadius};});
console.log("AT LOAD (top):",JSON.stringify(d));
await b.close(); s.close();
