import { chromium } from "playwright";
import http from "node:http"; import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs"; import { extname, join } from "node:path";
const ROOT=new URL("../_site/",import.meta.url).pathname;
const T={".html":"text/html",".css":"text/css",".js":"text/javascript",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2",".json":"application/json"};
const s=http.createServer(async(rq,rs)=>{try{let p=rq.url.split("?")[0];if(p.endsWith("/"))p+="index.html";let f=join(ROOT,p);if(!existsSync(f)&&existsSync(f+".html"))f+=".html";rs.writeHead(200,{"content-type":T[extname(f)]||"text/plain"});rs.end(await readFile(f));}catch{rs.writeHead(404);rs.end("x");}});
await new Promise(r=>s.listen(4559,r));
const EXE="/home/balnagowan/.cache/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell";
const b=await chromium.launch({executablePath:EXE,args:["--no-sandbox","--disable-gpu"]});
const pg=await b.newPage({viewport:{width:1280,height:900}});
const path=process.argv[2]||"/pages/eicr-software-uk.html";
await pg.goto("http://localhost:4559"+path,{waitUntil:"load"});
await pg.waitForTimeout(700);
const info=await pg.evaluate(()=>{const nav=document.querySelector("nav");const body=document.body;return {bodyClass:body.className,navRadius:nav?getComputedStyle(nav).borderTopLeftRadius:"NO NAV",navBg:nav?getComputedStyle(nav).backgroundImage.slice(0,40):"",wordCount:body.innerText.split(/\s+/).length,title:document.title};});
console.log(path,"->",JSON.stringify(info,null,2));
await pg.screenshot({path:"/tmp/claude-1000/-home-balnagowan-quickler-engine/7ba1eac7-26e9-49f0-a6d1-8dd163346506/scratchpad/seo-page.png"});
await b.close(); s.close();
